service: s3-final-lab

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole

functions:
  users:
    handler: handler.handler
    events:
      - s3:
          bucket: bucket-cloudcomputing-final-3265
          event: s3:ObjectCreated:*
          rules:
            - prefix: entrada-dados/
            - suffix: .json
      - s3:
          bucket: bucket-cloudcomputing-final-3265
          event: s3:ObjectRemoved:*
          rules:
            - prefix: entrada-dados/
            - suffix: .json